### ISSUE TITLE
关于调度，以及优化的问题

### ISSUE THREAD

**Issue by CaterpillarStudio** [filestar-project/lotus#14]
1、看到团队很努力开发了8G扇区，不过相对于隔壁fic的进度，好像有点慢，但是看到团队努力，辛苦了
2、能否把fil那边的调度集成一下呢，现在官方的调度对于挖矿硬件闲置的太大了，如果说要矿工去优化，那么隔壁的fic都做得很好了，我们这里能否去改进一下，顺便把sdr引入一下吧，虽然说会导致AMD再次领先，但为了网络发展，而不是考虑太旧的硬件了吧，新引入的矿工都是新硬件，3970X跑32G P1要4小时，真的真的太浪费资源了，这样分叉导致的浪费，真的不如去挖fil了

可能语气有得罪，不过都是希望项目好的小矿工，要是能改进下，那就非常感激了

**Comment by codefather-filestar** [comment]
感谢你的建议，后期会安排人力优化的，不过当下还有其他更有利于 FileStar 生态的事情要做，敬请期待。

**Comment by codefather-filestar** [comment]
multi core sdr is enabled
