### ISSUE TITLE
amd显卡5700xt不能使用，看了源码应该是bellperson没有升级

### ISSUE THREAD

**Issue by suency** [filestar-project/lotus#16]
用5700xt显卡在bellperson下面代码是可以跑通的 https://github.com/filecoin-project/bellperson
官方filecoin下的bellperson（版本0.12.3）是支持5700，但是在filestar下面用的版本是0.9.2（文档里面是不支持amd显卡的），请大神们什么时候升级一下bellperson，来支持下amd 5700xt显卡？谢谢

**Comment by filestar-moon** [comment]
可以通过环境变量的方式增加对某一款显卡的支持，如下，分别是显卡名称和核心数
export BELLMAN_CUSTOM_GPU="GeForce RTX 3090:10496"
