### ISSUE TITLE
ERROR	chain	chain/sync.go:235	Received block with impossibly large height 478596

### ISSUE THREAD

**Issue by jacktao2018** [filestar-project/lotus#17]
lotus daemon --import-snapshot filestar.car
同步car后，启动后报Received block with impossibly large height 478594

**Comment by codefather-filestar** [comment]
系统时间正常吗

**Comment by liangjishengzks** [comment]
@jacktao2018 或者你把lotus数据相关都删了，从新import下，如果还是不行的话，重启下系统试试

**Comment by jacktao2018** [comment]
> 系统时间正常吗

系统时间update一下，好了.非常感谢，
