### ISSUE TITLE
checksum mismatch in param

### ISSUE THREAD

**Issue by David-Qin** [filestar-project/lotus#27]
miner和worker启动的时候验证parms的时候有概率报checksum mismatch in param错误，设置param只读，然后清空缓存，重新运行就通过了

**Comment by codefather-filestar** [comment]
通常来说出现这种情况都是 `IPFS_GATEWAY`环境变量设置错了，确保设置为 `export IPFS_GATEWAY=https://filestar-proofs.s3.cn-east-1.jdcloud-oss.com/ipfs/`
