### ISSUE TITLE
A Security vulnerability to report

### ISSUE THREAD

**Issue by Al1ex** [filestar-project/lotus#9]
Hello, I found a serious security vulnerabilities. I want to know how to safely submit it to the project party(the Security page link is to filecoin not filestar).

**Comment by codefather-filestar** [comment]
Hi, thanks for report, please send the details to dev@filestar.net .

**Comment by Al1ex** [comment]
Yes, I have sent it to you. Please check it. If there is any problem that needs to be discussed and exchanged, it can be done by email




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "codefather-filestar"<notifications@github.com&gt;; 
发送时间: 2020年12月17日(星期四) 下午4:10
收件人: "filestar-project/lotus"<lotus@noreply.github.com&gt;; 
抄送: "Al1ex"<2084770716@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [filestar-project/lotus] A Security vulnerability to report (#9)





 
Hi, thanks for report, please send the details to dev@filestar.net .
